# Problem Set 3 - Computation
## Francesco Furno

## Problem 1

In [24]:
import numpy as np
from scipy import linalg as la

def QR(A):
    shape = A.shape
    Q = np.copy(A)
    R = np.zeros(shape)
    for i in range(shape[1]):
        R[i,i] = la.norm(Q[:,i])
        Q[:,i] = Q[:,i]/R[i,i]
        for j in np.arange(i+1,shape[1],1):
            R[i,j] = Q[:,j].T @ Q[:,i]
            Q[:,j] = Q[:,j] - R[i,j]*Q[:,i]
            
    return Q,R

A = np.random.randn(5,3)

Q,R = QR(A)    # My algo
Q1, R1 = la.qr(A, mode="economic")  # Scipy algo

print("My algorithm produces:", Q)
print("Scipy algorithm produces:",Q1)
print("My algorithm produces:", R)
print("Scipy algorithm produces:",R1)

print("Q is indeed orthogonal (up to rounding):")
print(Q.T@Q)

My algorithm produces: [[ 0.57086438  0.61044829  0.41103417]
 [ 0.50068287 -0.74200766  0.01220051]
 [-0.06581791  0.2662094  -0.78503839]
 [ 0.55809476  0.07658573 -0.44153388]
 [-0.32806821  0.00668583  0.14023057]]
Scipy algorithm produces: [[-0.57086438  0.61044829  0.41103417]
 [-0.50068287 -0.74200766  0.01220051]
 [ 0.06581791  0.2662094  -0.78503839]
 [-0.55809476  0.07658573 -0.44153388]
 [ 0.32806821  0.00668583  0.14023057]]
My algorithm produces: [[ 2.38469764  0.15042118  1.53757234]
 [ 0.          1.87287855 -0.81372117]
 [ 0.          0.          1.81150906]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
Scipy algorithm produces: [[-2.38469764 -0.15042118 -1.53757234]
 [ 0.          1.87287855 -0.81372117]
 [ 0.          0.          1.81150906]]
Q is indeed orthogonal (up to rounding):
[[  1.00000000e+00  -3.17143586e-17  -1.39018307e-16]
 [ -3.17143586e-17   1.00000000e+00   7.46884481e-17]
 [ -1.39018307e-16   7.46884481e-17   1.0000000

## Problem 2

In [45]:
def detQR(A):
    shape = A.shape
    if shape[0]!=shape[1]:
        print("Only square matrix accepted")
        return None        
    else:
        if la.det(A)==0:
            print("Only invertible matrix accepted")
            return None
        else:
            Q,R = QR(A)
            determinant = (la.det(Q)* la.det(R))
    return determinant

n = np.random.randint(1,20)
A = np.random.randn(n,n)

det = detQR(A)
det1 = la.det(A)

print("Determinant based on QR:")
print(det)
print("Numpy determinant:")
print(det1)

Determinant based on QR:
0.2891046925107528
Numpy determinant:
0.2891046925107529


In [46]:
B = np.random.randn(3,2)
detQR(B)

Only square matrix accepted


## Problem 3

In [ ]:
def solvelinsys(A,b):
    Q,R = QR(A)
    y = Q.T@b
    