# Problem Set 1 - Francesco Furno


# # Standard Libraries

## Problem 1

The function that takes as input a list of numbers and returns as output the minimum, the maximum and the average of such a list.

In [6]:
def function1(x):
    m, M, average = min(x), max(x), sum(x)/len(x)
    return m, M, average

I could write such a function in one line with the "lambda" function?

In [58]:
f1 = lambda x : min(x), max(x), sum(x)/len(x)

TypeError: 'int' object is not iterable

 ## Problem 2

First consider numbers:

In [10]:
x = 6 # Call the object (number) x
y = x
y = y + 1
x==y

False

Since the result is false it means that x and y are distinct objects, i.e. a copy of x had been created. Therefore, a number is an immutable data structure. Let's now consider strings:

In [57]:
word = "hello"
parola = word
parola = parola + "a"
parola==word

False

Since the result is false, strings are immutable objects. Let's now consider lists:

In [15]:
lista = [2,5,6]
llista = lista
llista.append(4)
llista == lista


True

Since the result is true, lists are mutable objects. Let's now consider tuples:

In [21]:
z = (2,3,5)
q = z
q = q+(1,)
q==z

False

Finally, let's consider dictionaries:

In [41]:
d = {'me': "Francesco", 'you' : "Instructor"}
e = d
e[1] = "a"
d==e

True

Therefore dictionaries are immutable objects.

## Problem 3

I have written a module called calculator.py. Now let's define the function that will allow me to compute the hypothenuse of a right triangle.

In [40]:
import calculator as calc
def hypotenuse(x,y):
    a = calc.product(x,x)
    b = calc.product(y,y)
    c = calc.sum(a,b)
    result = calc.squareroot(c)
    return result

Now, let's compute the hypotenuse of a right triangle with one side equal to 2 and the other one equal to 1:

In [35]:
hypotenuse(2,1)

2.23606797749979

# # Numpy

## Problem 1

In [71]:
import numpy as np
A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])

def product(x,y):
    solution = np.dot(x,y)
    print(solution)

product(A,B)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


## Problem 2

In [72]:
import numpy as np
A = np.array([[3, 1, 4],[1, 5, 9],[-5, 3, 1]])

def HC(A):
    result = - np.dot(np.dot(A,A),A) + 9 * np.dot(A,A) - 15 * A
    print(result)

HC(A)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Problem 3

In [73]:
A = np.ones(7)
A = np.triu(A)
print(A)

B1 = np.full(7,5)
B2 = np.tril(np.full(7, 6))
B = B1 - B2
print(B)
solution = A@ B
print(solution)

[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 0.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.]]
[[-1  5  5  5  5  5  5]
 [-1 -1  5  5  5  5  5]
 [-1 -1 -1  5  5  5  5]
 [-1 -1 -1 -1  5  5  5]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1 -1 -1]]
[[ -7.  -1.   5.  11.  17.  23.  29.]
 [ -6.  -6.   0.   6.  12.  18.  24.]
 [ -5.  -5.  -5.   1.   7.  13.  19.]
 [ -4.  -4.  -4.  -4.   2.   8.  14.]
 [ -3.  -3.  -3.  -3.  -3.   3.   9.]
 [ -2.  -2.  -2.  -2.  -2.  -2.   4.]
 [ -1.  -1.  -1.  -1.  -1.  -1.  -1.]]


## Problem 4

In [74]:
C = np.array([3, 4, 7, -1, -2, 6, -14, 25, 9])
C2 = np.copy(C)
C2[C2 < 0] = 0
print(C2)

[ 3  4  7  0  0  6  0 25  9]


# # Object-Oriented Programming

Let's define the Backpack class as in the notes.

In [60]:
class Backpack(object):
    def __init__(self,name):
        self.name = name
        self.content = []
        
    def put(self,item):
        self.content.append(item)
    
    def remove(self,item):
        self.content.remove(item)
    
        
my_backpack = Backpack("Steven")      
print(my_backpack.name)
my_backpack.name = "Frank"   # I can modify the attribute of my object after creation
print(my_backpack.name)
    
my_backpack.put("shirt")
my_backpack.put("trousers")
print(my_backpack.content)


    

Steven
Frank
['shirt', 'trousers']


## Problem 1

In [70]:
class Backpack(object):
    def __init__(self,name, color, max_size=5):
        self.name = name
        self.color = color
        self.max_size = max_size
        self.content = []
        
    def put(self,item):
        if len(self.content) >= self.max_size:
            print("Too many inputs")
        if len(self.content) < self.max_size:
            self.content.append(item)
    
    def remove(self,item):
        self.content.remove(item)
    
    def dump(self):
        self.content = []
        
mybackpack = Backpack("Invicta", "black",2)
mybackpack.put("ciao")
print(mybackpack.content)
mybackpack.put("hello")
print(mybackpack.content)

mybackpack.dump()
print(mybackpack.content)

['ciao']
['ciao', 'hello']
[]
